### ISSUE TITLE
Calendar view not displaying, ui components unresponsive. [v1.4.1]

### ISSUE THREAD

**Issue by Hrafnthor** [nextcloud/calendar#205]
### Steps to reproduce
1. Update of calendar from v1.4.0 to v1.4.1

### Expected behaviour
Date picker, period filter, calendar creator, central main view and subscription creation should work.

### Actual behaviour
* Date picker not loading, and showing only '{{dt | datepickerFilter:selectedView}}'
* Period filter buttons have no affect
* Calendar creation doesn't create a new calendar
* Subscription creation doesn't create a new subscription
* Main central calendar view is empty

### Server configuration
Linux - Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL 5.7.15

**PHP version:**
7.0.8

**Server version:** (see your admin page)
Nextcloud 10.0 (stable)

**Calendar version:** (see the apps page)
1.4.1

**Updated from an older installed version or fresh install:**
Updated from 1.4.0 to 1.4.1 through Nextcloud web interface.
Have also removed Calendar plugin and reinstalled it fresh to 1.4.1. Behavior persists

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Only Nextcloud's default list and Calendar 

**Are you using encryption:** 
yes

### Client configuration
**Browser:**
Firefox 49.0
Chome 53.0.2785.89 (64-bit)

**Operating system:**
Linux - Ubuntu 16.04

#### Browser log
On window load these are the logs. No activity during any button click or other interaction with Calendar UI components.
```
12:32:09.496 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. 1 calendar
12:32:11.952 JQMIGRATE: Migrate is installed, version 1.4.0 1 jquery-migrate.min.js:2:542

```
![selection_010](https://cloud.githubusercontent.com/assets/602070/20648402/d814f22c-b49d-11e6-8a22-5191aecc73ad.png)

**Comment by georgehrke** [comment]
please enable debug mode and check the browser log again

**Comment by sfulib** [comment]
I got the same issue and fixed by re-enabling the sharing option.

**Comment by georgehrke** [comment]
Indeed :/

<img width="960" alt="calendar - nextcloud chromium today at 12 06 52 am" src="https://cloud.githubusercontent.com/assets/1250540/20689885/c5118cb4-b5c7-11e6-829b-a83b9caf6c8c.png">

**Comment by georgehrke** [comment]
Disabling sharing is a tricky thing anyway, because it has no influence on the actual caldav sharing, but we need it to search for users and groups.

Best approach here from my pov:
- only show sharing option (search for users/groups) when sharing API is enabled
- make sure publishing works nevertheless with our without sharing API

What do you think @tcitworld ^

**Comment by tcitworld** [comment]
I first thought of requiring the Share API for the calendar to show up in the first place, but I guess people can use it as a personal calendar only on a server where the Share API has been disabled.

Your solution seems the best approach that we've got. Publishing should not be affected.

**Comment by georgehrke** [comment]
I actually forgot about the third option.
- Just reimplement the Share API's endpoint, that we use for the user / group querying and replace OC.SHARE.foobar constants with our own ones.

**Comment by tcitworld** [comment]
This adds complexity and requires us to maintain it. :/

**Comment by georgehrke** [comment]
Hm, yes.
It's quite a lot of code: https://github.com/nextcloud/server/blob/94004cf46bb676255c88a1f0d08866d3904945ec/apps/files_sharing/lib/Controller/ShareesAPIController.php

So let's stick to option 2 :)

**Comment by georgehrke** [comment]
fix is in #215

**Comment by lwt-pressy** [comment]
I got the same issue and it did not get fixed by re-enabling the sharing option inside Admin. The only help was going back to version 1.4.0

**Comment by georgehrke** [comment]
@lwt-pressy Please create a new issue using the entire issue template

**Comment by lwt-pressy** [comment]
done as #225

**Comment by benoitldr** [comment]
hey,
I have got the same issue and re-enabling the sharing option in admin didn't solve the problem as mentionned @lwt-pressy ...
