### ISSUE TITLE
Week Numbers in  Editor's date picker

### ISSUE THREAD

**Issue by Neuroplant** [nextcloud/calendar#2472]
### Steps to reproduce
1. Set "Language" to German
2. Set "Locale" to Germany(German)
3. Open Calendar
4. Open Calendar
5. open "+ New Event" assistent
6. Click on "from.." or "to.." field

### Expected behaviour
Weeks are counted in the German way (1st day of week is Monday, week ends on weekend, first week of year contains the 4th of January )

### Actual behaviour
US week numbers (Calendar view itself is OK)

### Calendar app
**Calendar app version:** 2.0.3

### Server configuration

**Operating system**: Ubuntu Server 18.04 LTS

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7.2.33

**Nextcloud Version:** 19.0.1

**Updated from an older installed version or fresh install:** updated

[...]

**Comment by georgehrke** [comment]
Need to verify, but this was most likely already fixed with https://github.com/nextcloud/calendar/pull/2286/files#diff-55414c46bbaf82480f70e458c5b0fbe1R52

**Comment by Neuroplant** [comment]
yes this looks exact the same
as written I am using current v2.0.3 where it is not fixed

**Comment by georgehrke** [comment]
This was indeed already fixed with #2286
