### ISSUE TITLE
Embedded public calendar does not display in firefox, but does in Chrome.

### ISSUE THREAD

**Issue by ds4a** [nextcloud/calendar#2603]
### Steps to reproduce
1.Create share link for calendar and copy embedding code
2.Place embedding code in public html file
3.Navigate to public html file URL using firefox

### Expected behaviour
Embedded calendar is displayed in browser

### Actual behaviour
The following text is displayed:
Public calendar does not exist
Maybe the share was deleted or has expired? 

### Calendar app
2.0.4

### Client configuration
Firefox 80.0.1
Ubuntu 18.04, Android 10

### Server configuration

Ubuntu 18.04

Nginx
PostgreSQL)
PHP version: 7.2

**Nextcloud Version:** 18.0.4

**Updated from an older installed version or fresh install: Updated

**List of activated apps:**

Accessibility
1.4.0
Featured
Activity
2.11.0
Featured
AppOrder
0.11.0
Audio Player
2.11.2
Auditing / Logging
1.8.0
Featured
Calendar
2.0.4
Featured
Checksum
0.4.5
Collaborative tags
1.8.0
Featured
Comments
1.8.0
Featured
Community Document Server
0.1.7
Contacts
3.3.0
Featured
Deck
1.0.5
Featured
Deleted files
1.8.0
Featured
External sites
3.5.0
Featured
External storage support
1.9.0
Featured
Federation
1.8.0
Featured
File sharing
1.10.1
Featured
First run wizard
2.7.0
Featured
Keeweb
0.6.2
Log Reader
2.3.0
Featured
Maps
0.1.6
Featured
Monitoring
1.8.0
Featured
Music
0.16.0
Nextcloud announcements
1.7.0
Featured
Notifications
2.6.0
Featured
ONLYOFFICE
6.0.0
Featured
Password policy
1.8.0
Featured
PDF viewer
1.7.0
Featured
Phone Sync
2.1.8
PhoneTrack
0.6.4
Photos
1.0.0
Featured
Plain text editor
2.11.0
Privacy
1.2.0
Featured
Radio
0.6.6
Recommendations
0.6.0
Featured
Right click
0.15.2
Featured
Share by mail
1.8.0
Featured
Support
1.1.0
Featured
Talk
8.0.11
Featured
Text
2.0.0
Featured
Theming
1.9.0
Featured
Update notification
1.8.0
Featured
Versions
1.11.0
Featured
Video player 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) :
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Proxying an event bus of version 1.1.2 with 0.2.1 notifications.js:21:13435
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
Some cookies are misusing the recommended “SameSite“ attribute 8
Cookie “__Host-nc_sameSiteCookielax” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. notifications
Cookie “__Host-nc_sameSiteCookiestrict” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. notifications
Cookie “__Host-nc_sameSiteCookielax” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. notifications
Cookie “__Host-nc_sameSiteCookiestrict” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. notifications
Cookie “__Host-nc_sameSiteCookielax” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. REDACTED
Cookie “__Host-nc_sameSiteCookiestrict” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. REDACTED
Cookie “__Host-nc_sameSiteCookielax” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. REDACTED
Cookie “__Host-nc_sameSiteCookiestrict” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. REDACTED
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/core/js/dist/main.js?v=0e621ca1-24
Source Map URL: main.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/files_videoplayer/js/main.js?v=0e621ca1-24
Source Map URL: main.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/files_sharing/js/dist/main.js?v=0e621ca1-24
Source Map URL: main.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/calendar/js/chunks/calendar.16.41d8dd75db3e20284dc9.js
Source Map URL: calendar.16.41d8dd75db3e20284dc9.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/notifications/js/notifications.js?v=0e621ca1-24
Source Map URL: notifications.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/calendar/js/calendar.js?v=0e621ca1-24
Source Map URL: calendar.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/calendar/js/chunks/calendar.93.bb7cf6dd46d8cc5e2779.js
Source Map URL: calendar.93.bb7cf6dd46d8cc5e2779.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/core/js/dist/main.js?v=0e621ca1-24
Source Map URL: main.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/notifications/js/notifications.js?v=0e621ca1-24
Source Map URL: notifications.js.map
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://EXAMPLE.COM/apps/calendar/js/calendar.js?v=0e621ca1-24
Source Map URL: calendar.js.map



{"Request headers (826 B)":{"headers":[{"name":"Accept","value":"*/*"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Accept-Language","value":"en-GB,en;q=0.5"},{"name":"Cache-Control","value":"max-age=0"},{"name":"Connection","value":"keep-alive"},{"name":"Content-Length","value":"4983"},{"name":"Content-Type","value":"application/xml; charset=utf-8"},{"name":"Cookie","value":"oc_music_volume=60; oc_sessionPassphrase=FpCrOVBOiMAcuOiE1dEbl0%2FohEB2gKARW0FvYC0WHe03iBUiPru67vljImYc7gwFQiGzxqk4UVZLeHdq%2B%2FNv6aSiWDVCtlR608YVI2OKhVVivEseqMfrbr8bfyMk1R%2Fv; ocm0ypzdwozy=7k3vk36ltg38o2csni7fmil71k"},{"name":"Depth","value":"0"},{"name":"Host","value":"example.com"},{"name":"Origin","value":"https://example.com"},{"name":"requesttoken","value":"A7KFjQnGLP44Lzh9+SlXhxRZdSuJhIM0LqSTh06hWnQ=:M+ThuHO2b79hX3sNu25j0mw4JEH66slnV4+893rACA4="},{"name":"TE","value":"Trailers"},{"name":"User-Agent","value":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"},{"name":"X-NC-CalDAV-Webcal-Caching","value":"On"},{"name":"X-Requested-With","value":"XMLHttpRequest"}]}}

**Comment by tcitworld** [comment]
Unfortunately this has been fixed in server, but only for Nextcloud 19.

**Comment by ds4a** [comment]
Have upgraded to NC 19.0.3 - Issue still persists as previously reported on desktop.
Embedded calendar does NOT display in Firefox 80.0.1 on Ubuntu 18.04 Desktop
Calendar does display as expected in Chrome, Opera, Epiphany, Firefox 80.1.3 on Android 10.
