### ISSUE TITLE
Blank page on calendar

### ISSUE THREAD

**Issue by ckykenken** [nextcloud/calendar#2775]
![image](https://user-images.githubusercontent.com/26035978/103456560-479b5d80-4d32-11eb-92c0-b03e3c49cee1.png)

 

### Steps to reproduce
1. Navigate to the calendar page

### Expected behaviour
The calendar grid should appear next to the list of calendars

### Actual behaviour
The calendar grid is absent

### Calendar app
**Calendar app version:** 2.1.2

**CalDAV-clients used:** None

### Client configuration
**Browser:** Every browser including Chromium-based and Firefox
**Operating system:** Any

### Server configuration

**Operating system**: Ubuntu 18.04.4

**Web server:** Snap package

**Database:** MySQL

**PHP version:** 7.2.24

**Nextcloud Version:** 20.0.4

**Updated from an older installed version or fresh install:** Fresh Install

**List of activated apps:**

  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - drawio: 0.9.8
  - external: 3.7.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_pdfviewer: 2.0.1
  - files_retention: 1.9.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - ldap_contacts_backend: 1.0.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - spreed: 10.0.4
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**
```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hypernology.com",
            "10.68.165.94",
            "hk165094cloud01.hypernite.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "cloud.hypernology.com",
        "overwritehost": "cloud.hypernology.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 2
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Wed Dec 23 10:40:44.203767 2020] [ssl:warn] [pid 3351:tid 139962406639488] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Wed Dec 23 10:40:44.204073 2020] [lbmethod_heartbeat:notice] [pid 3351:tid 139962406639488] AH02282: No slotmem from mod_heartmonitor
[Wed Dec 23 10:40:44.204747 2020] [mpm_event:notice] [pid 3351:tid 139962406639488] AH00489: Apache/2.4.46 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 23 10:40:44.204762 2020] [core:notice] [pid 3351:tid 139962406639488] AH00094: Command line: 'httpd -d /snap/nextcloud/24940 -D FOREGROUND'
[Wed Dec 23 10:40:44.207931 2020] [unixd:alert] [pid 3354:tid 139962406639488] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 10:40:44.207934 2020] [unixd:alert] [pid 3355:tid 139962406639488] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 10:40:44.207936 2020] [unixd:alert] [pid 3356:tid 139962406639488] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 10:41:43.868172 2020] [unixd:alert] [pid 7642:tid 139962406639488] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:12:35.648964 2020] [mpm_event:notice] [pid 3351:tid 139962406639488] AH00491: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Wed Dec 23 12:13:27.883679 2020] [ssl:warn] [pid 3311:tid 140180686780288] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Wed Dec 23 12:13:27.883997 2020] [lbmethod_heartbeat:notice] [pid 3311:tid 140180686780288] AH02282: No slotmem from mod_heartmonitor
[Wed Dec 23 12:13:27.884560 2020] [mpm_event:notice] [pid 3311:tid 140180686780288] AH00489: Apache/2.4.46 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 23 12:13:27.884576 2020] [core:notice] [pid 3311:tid 140180686780288] AH00094: Command line: 'httpd -d /snap/nextcloud/24940 -D FOREGROUND'
[Wed Dec 23 12:13:27.892504 2020] [unixd:alert] [pid 3315:tid 140180686780288] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:13:27.892508 2020] [unixd:alert] [pid 3313:tid 140180686780288] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:13:27.892511 2020] [unixd:alert] [pid 3314:tid 140180686780288] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:13:54.408238 2020] [unixd:alert] [pid 4418:tid 140180686780288] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:24:24.515681 2020] [proxy_fcgi:error] [pid 3313:tid 140179947910912] [client 10.68.2.174:53134] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.515724 2020] [proxy_fcgi:error] [pid 3313:tid 140179947910912] (104)Connection reset by peer: [client 10.68.2.174:53134] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.517947 2020] [proxy_fcgi:error] [pid 3314:tid 140179293574912] [client 10.68.165.94:43626] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.517992 2020] [proxy_fcgi:error] [pid 3314:tid 140179293574912] (104)Connection reset by peer: [client 10.68.165.94:43626] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.523335 2020] [proxy_fcgi:error] [pid 4418:tid 140180417672960] [client 10.68.2.174:53147] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.523376 2020] [proxy_fcgi:error] [pid 4418:tid 140180417672960] (104)Connection reset by peer: [client 10.68.2.174:53147] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.524114 2020] [proxy_fcgi:error] [pid 4418:tid 140180509927168] [client 10.68.165.94:43638] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.524129 2020] [proxy_fcgi:error] [pid 4418:tid 140180509927168] (104)Connection reset by peer: [client 10.68.165.94:43638] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.524992 2020] [proxy_fcgi:error] [pid 3314:tid 140179268396800] [client 10.68.2.174:53183] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.525009 2020] [proxy_fcgi:error] [pid 3314:tid 140179268396800] (104)Connection reset by peer: [client 10.68.2.174:53183] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.526809 2020] [proxy_fcgi:error] [pid 4418:tid 140180375709440] [client 10.68.165.94:43646] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.526831 2020] [proxy_fcgi:error] [pid 4418:tid 140180375709440] (104)Connection reset by peer: [client 10.68.165.94:43646] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.528687 2020] [proxy_fcgi:error] [pid 3314:tid 140179285182208] [client 10.68.165.94:43630] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.528704 2020] [proxy_fcgi:error] [pid 3314:tid 140179285182208] (104)Connection reset by peer: [client 10.68.165.94:43630] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.534294 2020] [proxy_fcgi:error] [pid 3314:tid 140179301967616] [client 10.68.165.94:43634] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.534323 2020] [proxy_fcgi:error] [pid 3314:tid 140179301967616] (104)Connection reset by peer: [client 10.68.165.94:43634] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.534471 2020] [proxy_fcgi:error] [pid 3314:tid 140179335538432] [client 10.68.2.174:60684] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.534479 2020] [proxy_fcgi:error] [pid 3314:tid 140179335538432] (104)Connection reset by peer: [client 10.68.2.174:60684] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.543416 2020] [proxy_fcgi:error] [pid 4418:tid 140180392494848] [client 10.68.165.94:43642] AH01067: Failed to read FastCGI header
[Wed Dec 23 12:24:24.543437 2020] [proxy_fcgi:error] [pid 4418:tid 140180392494848] (104)Connection reset by peer: [client 10.68.165.94:43642] AH01075: Error dispatching request to : 
[Wed Dec 23 12:24:24.888880 2020] [mpm_event:notice] [pid 3311:tid 140180686780288] AH00491: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Wed Dec 23 12:25:49.681962 2020] [ssl:warn] [pid 3334:tid 140498612705152] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Wed Dec 23 12:25:49.682295 2020] [lbmethod_heartbeat:notice] [pid 3334:tid 140498612705152] AH02282: No slotmem from mod_heartmonitor
[Wed Dec 23 12:25:49.682908 2020] [mpm_event:notice] [pid 3334:tid 140498612705152] AH00489: Apache/2.4.46 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Wed Dec 23 12:25:49.682930 2020] [core:notice] [pid 3334:tid 140498612705152] AH00094: Command line: 'httpd -d /snap/nextcloud/24940 -D FOREGROUND'
[Wed Dec 23 12:25:49.690810 2020] [unixd:alert] [pid 3335:tid 140498612705152] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:25:49.690811 2020] [unixd:alert] [pid 3336:tid 140498612705152] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:25:49.690812 2020] [unixd:alert] [pid 3337:tid 140498612705152] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Wed Dec 23 12:25:51.685527 2020] [unixd:alert] [pid 3776:tid 140498612705152] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Thu Dec 24 22:51:08.599555 2020] [mpm_event:notice] [pid 3334:tid 140498612705152] AH00491: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 24 22:52:12.082384 2020] [ssl:warn] [pid 26217:tid 140591818147712] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Dec 24 22:52:12.082915 2020] [lbmethod_heartbeat:notice] [pid 26217:tid 140591818147712] AH02282: No slotmem from mod_heartmonitor
[Thu Dec 24 22:52:12.083457 2020] [mpm_event:notice] [pid 26217:tid 140591818147712] AH00489: Apache/2.4.46 (Unix) OpenSSL/1.1.1 configured -- resuming normal operations
[Thu Dec 24 22:52:12.083474 2020] [core:notice] [pid 26217:tid 140591818147712] AH00094: Command line: 'httpd -d /snap/nextcloud/25276 -D FOREGROUND'
[Thu Dec 24 22:52:12.086021 2020] [unixd:alert] [pid 26220:tid 140591818147712] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Thu Dec 24 22:52:12.086036 2020] [unixd:alert] [pid 26219:tid 140591818147712] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Thu Dec 24 22:52:12.086821 2020] [unixd:alert] [pid 26221:tid 140591818147712] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Fri Dec 25 03:04:14.880871 2020] [unixd:alert] [pid 27020:tid 140591818147712] AH02155: getpwuid: couldn't determine user name from uid 4294967295, you probably need to modify the User directive
[Sun Dec 27 00:00:38.170258 2020] [mpm_event:notice] [pid 26217:tid 140591818147712] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

```

#### Log file (data/nextcloud.log)
```
{"reqId":"UyghHwzQySO4XrkzUMiO","level":3,"time":"2020-12-28T16:38:56+00:00","remoteAddr":"10.68.128.1","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/mindmap.svg?v=0","message":{"Exception":"Error","Message":"file_get_contents(): Filename cannot be empty at /snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php#232","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(): Filename cannot be empty","/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php",232,{"app":"core","image":"filetypes/mindmap.svg","imageFile":false}]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php","line":232,"function":"file_get_contents","args":[""]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/Controller/IconController.php","line":93,"function":"colorSvg","class":"OCA\\Theming\\IconBuilder","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"app":"core","image":"filetypes/mindmap.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/snap/nextcloud/25276/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/25276/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}
{"reqId":"6XKSki1QaDWCOGV2MrJx","level":3,"time":"2020-12-28T16:39:20+00:00","remoteAddr":"10.68.128.1","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/mindmap.svg?v=0","message":{"Exception":"Error","Message":"file_get_contents(): Filename cannot be empty at /snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php#232","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(): Filename cannot be empty","/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php",232,{"app":"core","image":"filetypes/mindmap.svg","imageFile":false}]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php","line":232,"function":"file_get_contents","args":[""]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/Controller/IconController.php","line":93,"function":"colorSvg","class":"OCA\\Theming\\IconBuilder","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"app":"core","image":"filetypes/mindmap.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/snap/nextcloud/25276/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/25276/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}
{"reqId":"FqKDjvfD6zuunjjbE58p","level":3,"time":"2020-12-28T16:39:23+00:00","remoteAddr":"10.68.128.1","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/mindmap.svg?v=0","message":{"Exception":"Error","Message":"file_get_contents(): Filename cannot be empty at /snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php#232","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(): Filename cannot be empty","/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php",232,{"app":"core","image":"filetypes/mindmap.svg","imageFile":false}]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php","line":232,"function":"file_get_contents","args":[""]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/Controller/IconController.php","line":93,"function":"colorSvg","class":"OCA\\Theming\\IconBuilder","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"app":"core","image":"filetypes/mindmap.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/snap/nextcloud/25276/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/25276/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}
{"reqId":"80Lc5HfHzKVJFMNSmykm","level":3,"time":"2020-12-28T16:39:32+00:00","remoteAddr":"10.68.128.1","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/mindmap.svg?v=0","message":{"Exception":"Error","Message":"file_get_contents(): Filename cannot be empty at /snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php#232","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(): Filename cannot be empty","/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php",232,{"app":"core","image":"filetypes/mindmap.svg","imageFile":false}]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php","line":232,"function":"file_get_contents","args":[""]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/Controller/IconController.php","line":93,"function":"colorSvg","class":"OCA\\Theming\\IconBuilder","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"app":"core","image":"filetypes/mindmap.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/snap/nextcloud/25276/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/25276/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}
{"reqId":"J8qDux970rSON6l0dpmd","level":3,"time":"2020-12-28T17:18:10+00:00","remoteAddr":"10.68.30.109","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/mindmap.svg?v=0","message":{"Exception":"Error","Message":"file_get_contents(): Filename cannot be empty at /snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php#232","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(): Filename cannot be empty","/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php",232,{"app":"core","image":"filetypes/mindmap.svg","imageFile":false}]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/IconBuilder.php","line":232,"function":"file_get_contents","args":[""]},{"file":"/snap/nextcloud/25276/htdocs/apps/theming/lib/Controller/IconController.php","line":93,"function":"colorSvg","class":"OCA\\Theming\\IconBuilder","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"app":"core","image":"filetypes/mindmap.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/snap/nextcloud/25276/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/mindmap.svg"]},{"file":"/snap/nextcloud/25276/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/25276/htdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}
{"reqId":"jjHB0Fi76mcPtIVU0O9Y","level":2,"time":"2020-12-28T17:22:06+00:00","remoteAddr":"10.68.30.109","user":"5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","app":"dav","method":"MKCOL","url":"/remote.php/dav/calendars/5DC03F6C-31B5-4B21-9A67-30B25A57B2C3/calendargooglecom-2","message":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `GET https://calendar.google.com/calendar/ical/ansont1112%40gmail.com/public/basic.ics` resulted in a `404 Not Found` response:\n<html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><ti (truncated...)\n","Code":404,"Trace":[{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":65,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":[{"__class__":"GuzzleHttp\\Psr7\\Request"},"*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":203,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":156,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":[1,"*** sensitive parameter replaced ***",[{"__class__":"GuzzleHttp\\Promise\\Promise"},{"__class__":"Closure"},null]]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":47,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":246,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":223,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":267,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":225,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/guzzle/src/Client.php","line":183,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/Http/Client/Client.php","line":233,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https://calendar.google.com/calendar/ical/ansont1112%40gmail.com/public/basic.ics",{"verify":"/var/snap/nextcloud/common/nextcloud/data/files_external/rootcerts.crt","timeout":30,"allow_redirects":{"redirects":10},"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"nextcloud":{"allow_local_address":false},"headers":{"User-Agent":"Nextcloud Server Crawler","Accept-Encoding":"gzip"},"synchronous":true}]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php","line":238,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https://calendar.google.com/calendar/ical/ansont1112%40gmail.com/public/basic.ics",{"allow_redirects":{"redirects":10},"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"nextcloud":{"allow_local_address":false}}]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php","line":99,"function":"queryWebcalFeed","class":"OCA\\DAV\\CalDAV\\WebcalCaching\\RefreshWebcalService","type":"->","args":[{"id":"4","uri":"calendargooglecom-2","principaluri":"principals/users/5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","source":"https://calendar.google.com/calendar/ical/ansont1112%40gmail.com/public/basic.ics","lastmodified":"1609176126","{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set":{"__class__":"Sabre\\CalDAV\\Xml\\Property\\SupportedCalendarComponentSet"},"{http://sabredav.org/ns}sync-token":"1","{DAV:}displayname":"calendar.google.com","{http://apple.com/ns/ical/}calendar-order":"0","{http://apple.com/ns/ical/}calendar-color":"#499AA2"},[]]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/AppInfo/Application.php","line":302,"function":"refreshSubscription","class":"OCA\\DAV\\CalDAV\\WebcalCaching\\RefreshWebcalService","type":"->","args":["principals/users/5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","calendargooglecom-2"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"OCA\\DAV\\AppInfo\\{closure}","class":"OCA\\DAV\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/lib/private/EventDispatcher/SymfonyAdapter.php","line":85,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/CalDAV/CalDavBackend.php","line":2147,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/CalDAV/CalendarHome.php","line":251,"function":"createSubscription","class":"OCA\\DAV\\CalDAV\\CalDavBackend","type":"->","args":["principals/users/5DC03F6C-31B5-4B21-9A67-30B25A57B2C3","calendargooglecom-2",{"{DAV:}displayname":"calendar.google.com","{http://apple.com/ns/ical/}calendar-color":"#499AA2","{http://owncloud.org/ns}calendar-enabled":"1","{http://calendarserver.org/ns/}source":{"__class__":"Sabre\\DAV\\Xml\\Property\\Href"}}]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/CalDAV/CalendarHome.php","line":84,"function":"createExtendedCollection","class":"Sabre\\CalDAV\\CalendarHome","type":"->","args":["calendargooglecom-2",{"__class__":"Sabre\\DAV\\MkCol"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":1206,"function":"createExtendedCollection","class":"OCA\\DAV\\CalDAV\\CalendarHome","type":"->","args":["calendargooglecom-2",{"__class__":"Sabre\\DAV\\MkCol"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":586,"function":"createCollection","class":"Sabre\\DAV\\Server","type":"->","args":["calendars/5DC03F6C-31B5-4B21-9A67-30B25A57B2C3/calendargooglecom-2",{"__class__":"Sabre\\DAV\\MkCol"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpMkcol","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:MKCOL",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/snap/nextcloud/25276/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/25276/htdocs/remote.php","line":167,"args":["/snap/nextcloud/25276/htdocs/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/snap/nextcloud/25276/htdocs/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"CustomMessage":"Subscription 4 could not be refreshed due to a network error"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":"20.0.4.0"}

```

#### Browser log
```

{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hypernology.com",
            "10.68.165.94",
            "hk165094cloud01.hypernite.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "cloud.hypernology.com",
        "overwritehost": "cloud.hypernology.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 2
    }
}

```

**Comment by Quix0r** [comment]
Well, have you checked browser console? I get this here: `ReferenceError: ResizeObserver is not defined` and I think your ticket's title should be renamed.

**Comment by Quix0r** [comment]
And seems to be a duplicate of #2757 ?

**Comment by muzzah** [comment]
I am also seeing this.

**Comment by jim-perkins** [comment]
for me and others it works with firefox but not in chrome(ium)
https://www.reddit.com/r/NextCloud/comments/kro77s/after_recent_update_calendar_blank_on_chromium/

**Comment by muzzah** [comment]
My problem here was due to path problems. I am using docker and specified a  bind path for the html directory and a different bind path for the custom_app directory. If you do this, then you must update the nginx config (or whatever is serving your nextcloud server) with this information so that the path for apps/config correctly points to your custom_app path.

Devs, it woudl be great if you actually added this to the docs. I can see many people having this problem and there doesnt seem to be any documentation for this

**Comment by kernal64** [comment]
Same here, works with Firefox but not with Chrome.

Versions:
OS: Manjaro Linux
Mozilla Firefox: 84.0.1 (64-Bit)
Google Chrome: 80.0.3987.132 (Offizieller Build) (64-Bit)
Nextcloud: 20.0.4 (in Docker)
NC Calendar: 2.1.3

I have NO different path for my custom_app directory. I can add more info, when needed.

**Comment by kernal64** [comment]
As I wanted to move from Chrome to Brave anyway, I just tested it right now with Brave and it's working.

Version: Version 1.18.78 Chromium: 87.0.4280.141 (Offizieller Build) unknown (64-Bit)

**Comment by syntron** [comment]
(I did post this in #2725 but this was closed)

I'm seeing this using calendar 2.1.3

working: Chromium (87.0.4280.88)
not working: falkon (3.1.0 / QtWebEngine 5.12.7) <= my default browser

using nextcloud 20.0.4.0; tasks and contacts seems to be fine

it was working before the latest update (2.1.2 => 2.1.3)

falkon console log:

index.js:46 No OC found
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
notifications-main.js?v=649afad2-3:303 Notifications permissions denied
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
calendar.js?v=649afad2-3:2 [INFO] calendar:
Initial settings:
- AppVersion: 2.1.3
- EventLimit: true
- FirstRun: false
- ShowWeekNumbers: true
- ShowTasks: true
- ShowWeekends: true
- SkipPopover: false
- SlotDuration: 00:30:00
- TalkEnabled: true
- TasksEnabled: true
- Timezone: automatic

{app: "calendar", uid: "matthias"}
calendar.js?v=649afad2-3:2 [DEBUG] calendar: The calendar app is using version 2.2019c of the timezone database
{app: "calendar", uid: "matthias"}
DevTools failed to parse SourceMap: https://[...nextcloud...]/apps/notifications/js/notifications-main.js.map?v=7e353c6…
calendar.js?v=649afad2-3:2 TypeError: e.replaceAll is not a function
at Mp (calendar.js?v=649afad2-3:2)
at i.options (calendar.js?v=649afad2-3:2)
at vn.get (calendar.js?v=649afad2-3:2)
at vn.evaluate (calendar.js?v=649afad2-3:2)
at i.options (calendar.js?v=649afad2-3:2)
at i.ls (calendar.js?v=649afad2-3:2)
at i.e._render (calendar.js?v=649afad2-3:2)
at i.r (calendar.js?v=649afad2-3:2)
at vn.get (calendar.js?v=649afad2-3:2)
at new vn (calendar.js?v=649afad2-3:2)
calendar.js?v=649afad2-3:2 TypeError: Cannot read property '$el' of undefined
at i.mounted (calendar.js?v=649afad2-3:2)
at He (calendar.js?v=649afad2-3:2)
at sn (calendar.js?v=649afad2-3:2)
at Object.insert (calendar.js?v=649afad2-3:2)
at x (calendar.js?v=649afad2-3:2)
at Dn.patch (calendar.js?v=649afad2-3:2)
at Dn.e._update (calendar.js?v=649afad2-3:2)
at Dn.r (calendar.js?v=649afad2-3:2)
at vn.get (calendar.js?v=649afad2-3:2)
at new vn (calendar.js?v=649afad2-3:2)
session-heartbeat.js:97 session heartbeat polling started
public.js:30 Files_PDFViewer initialized for public page
{isPublicPage: null, canDownload: true, isSecureViewerAvailable: false}
[Violation] Forced reflow while executing JavaScript took 126ms
23
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
[... repeated...]
calendar.js?v=649afad2-3:2 [INFO] calendar: Updated moment locale: de
{app: "calendar", uid: "matthias"}
ConsoleLogger.js:42 [DEBUG] unified-search: Unified Search initialized with the following providers
{0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, 10: {…}, 11: {…}, 12: {…}, 13: {…}, 14: {…}, 15: {…}, 16: {…}, app: "unified-search", uid: "matthias"}
calendar.js?v=649afad2-3:2 [DEBUG] calendar: Current user principal is /remote.php/dav/principals/users/matthias/
{app: "calendar", uid: "matthias"}
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
[... repeated...]

**Comment by dschrempf** [comment]
I have the same issue on Arch Linux, Nextcloud version 20.0.4-1, after update to calendar version 2.1.3.

The console error is:
```
TypeError: e.replaceAll is not a function
    at Mp (localeProvider.js:36)
    at i.options (CalendarGrid.vue:127)
    at vn.get (vue.runtime.esm.js:4479)
    at vn.evaluate (vue.runtime.esm.js:4584)
    at i.options (vue.runtime.esm.js:4836)
    at i.ls (CalendarGrid.vue?a26b:7)
    at i.e._render (vue.runtime.esm.js:3548)
    at i.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)
```

and
```
vue.runtime.esm.js:1888 TypeError: Cannot read property '$el' of undefined
    at i.mounted (CalendarGrid.vue:203)
    at He (vue.runtime.esm.js:1854)
    at sn (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
    at x (vue.runtime.esm.js:6346)
    at Dn.__patch__ (vue.runtime.esm.js:6565)
    at Dn.e._update (vue.runtime.esm.js:3945)
    at Dn.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)
```

**Comment by PatriceVigier** [comment]
White page on Firefox 69.0.3
The console error is
TypeError: "e.replaceAll is not a function"
and
TypeError: "this.$refs.fullCalendar is undefined"

Work on Chrome 87

**Comment by The-Compiler** [comment]
Likely fixed by #2822?

**Comment by jim-perkins** [comment]
Just updated Nextcloud to 20.0.6, which included a Calendar update to version 2.1.3.

I still have a blank right side with chromium Version 80.0.3987.7 (Official Build) Built on Ubuntu , running on Ubuntu 20.04 (64-bit)

Did see a bug fix in the changelog related to this issue. It didnt work for me. Fix blank page on browsers without support for ResizeObserver #2620
![Screenshot from 2021-01-26 20-44-13](https://user-images.githubusercontent.com/6559269/105935346-6e8a3e00-6017-11eb-83b7-02d4debdc98a.png)

**Comment by tcitworld** [comment]
@jim-perkins Your issue has been fixed in #2822 (not yet released).

Ubuntu 20.04 now redistributes Chromium through snaps and versions > 85 don't have this issue.

**Comment by jim-perkins** [comment]
@tcitworld .  thanks for the reply.  I can confirm that updating chromium to 'Version 89.0.4389.9 (Official Build) Built on Ubuntu , running on Ubuntu 20.04 (64-bit)' .  yea I am snap averse :-)

**Comment by rysiekpl** [comment]
It's been a month, any chance this will get resolved in a release anytime soon? For some of us switching a browser is not an option, and Firefox is still one of the main browsers out there.

**Comment by PatriceVigier** [comment]
and Firefox is a browser that respect your private life, what Chrome or MS do not, this is why it is important to support them

**Comment by rysiekpl** [comment]
Duplicate of #2734

**Comment by tcitworld** [comment]
Fixed in #2822.
