### ISSUE TITLE
The size of 15 minute events overlap

### ISSUE THREAD

**Issue by goebbe** [nextcloud/calendar#3521]
I believe the size of the event should respect the start-time and end-time.
I.e. an event that stops at 14:00h should never overlap with an event that starts at 14:00h.

In short events, the solution for the title could be to add the title of the event in the first line, if there is not enough space for the title in the second line.  

Look at the following screenshot. First impression is that there is an overlap between events: 

![Screenshot from 2021-09-30 15-28-19](https://user-images.githubusercontent.com/35854226/135464140-4b451a6d-43c0-4688-a039-c4f90c855766.png)

_Originally posted by @goebbe in https://github.com/nextcloud/calendar/issues/2853#issuecomment-931326894_

**Comment by miku86** [comment]
Hey there,

this seems to be a problem with 15min-appointments.

When I increase the duration from 15min to 45min while moving the next appointment, it turns into the UI-problem from #2853.

15min:

![2021-10-04_15-45](https://user-images.githubusercontent.com/7271016/135862906-58b85c7b-0da0-42d0-9673-0a016138cb16.png)

45min: 

![2021-10-04_15-45_1](https://user-images.githubusercontent.com/7271016/135862941-75ef1278-c1a4-4412-9b53-6c186b15dc9e.png)


```
Nextcloud 21.0.0
Calendar 2.3.4
```

Greetings
Michael

**Comment by szaimen** [comment]
I think this was fixed in the meantime. Couldnt reproduce this anymore

**Comment by miku86** [comment]
> I think this was fixed in the meantime. Couldnt reproduce this anymore

No, it is not fixed.

I updated  Nextcloud to 23.0.0 and  Calendar to 3.0.1 and it is still the same behaviour as in my previous comment.

**Comment by joshtrichards** [comment]
Agreed. Current behavior is essentially the same:

![Image](https://github.com/user-attachments/assets/65bf9f9d-6dc6-4f00-9b20-8e67cd2d767b)

Related: #3121

**Comment by SebastianKrupinski** [comment]
Closing this as the event view has been changed since the last comment

<img width="437" height="182" alt="Image" src="https://github.com/user-attachments/assets/81c30608-d88f-4620-9e35-5903fae8a3e3" />

**Comment by goebbe** [comment]
@SebastianKrupinski This issue is about **15-minute Events** - which is not reflected in the latest screenshot. 
**Example with the following events:** 
event 1: 8:00-8:15
event 2: 8:15-8:45 
At least on my managed Nextcloud, (31.0.9) delivered by hosting.de - which, to my knowledge, uses the new event view, the reported issue is not resolved.  
The two events are not displayed, as event2 is following event1. 
Graphically, it looks like event1 does not end before event2 starts - which is a wrong representation of the events. 

<img width="360" height="109" alt="Image" src="https://github.com/user-attachments/assets/35a0bece-1144-476b-b94d-3415d2cb6b7b" />

**Comment by SebastianKrupinski** [comment]
Hi @goebbe 

Ah, I didn't realize this was in regards to short events. But those do align properly now also.

This has been changed in Calendar v6.0. (NC32). although my test screen capture is from v6.1

<img width="1142" height="160" alt="Image" src="https://github.com/user-attachments/assets/5a7cec09-0e4d-4265-bee1-5d2b64fb88bd" />

**Comment by goebbe** [comment]
@SebastianKrupinski  Thanks for looking into this!
It might be that we are talking about two related but distinct issues. 
My original concern was about the **vertical** "overlap" of events, that was due to the fact that the height of the events (colored boxes) did not end at the correct time. 
When I put a 15-Minute event at 8:45 - the boxes should end at 9:00 and not at 9:15. This makes it hard to spot, that I will be available from 9:00.  

Looking at your screenshot, I believe this issue is still present. 

<img width="314" height="165" alt="Image" src="https://github.com/user-attachments/assets/66dc9691-f316-47b1-b5e9-745aa3af6a3c" />

**Comment by SebastianKrupinski** [comment]
Okay, i agree this is still an issue. 

<img width="1163" height="163" alt="Image" src="https://github.com/user-attachments/assets/a5d5220c-09bb-4634-9158-2f8cfc83fac3" />

**Comment by goebbe** [comment]
Here are two example of different calendars and how they display 15-minute events: 

<img width="306" height="230" alt="Image" src="https://github.com/user-attachments/assets/d8d09a4f-c224-4345-90a5-7a8a7849069b" />

And here is Thunderbirds calendar view: 
<img width="357" height="254" alt="Image" src="https://github.com/user-attachments/assets/42194a56-094f-46a1-ad31-9d6849fe2d01" />

**Comment by SebastianKrupinski** [comment]
I like the second option.

Development notes:

Full Calendar
eventOverlap: false ???

**Comment by goebbe** [comment]
In my humble opinion, a 15-minutes event should also graphically appear notably shorter (more dense) than a 30-minute event.
This could probably be achieved by (a tasteful) choice of "lesss padding".  

E.g. in the Thunderbird screenshot: It would be helpful if the upper and lower padding of "eventlongname 6" would be smaller. With smaller padding, one could immediately tell that this is an event that is shorter than "event 7". 

Also, showing the starting AND the end time of events is not very helpful, when you have many events with a short duration.
