### ISSUE TITLE
Calendar widget is empty after update to 27.1.0

### ISSUE THREAD

**Issue by ralfbgithub** [nextcloud/calendar#5477]
### Steps to reproduce

1. update from 27.0.2 to27.1.0
2. Calendar widget is empty
3.

### Expected behavior

 Calendar widget should show upcoming events

### Actual behaviour

Calendar widget is empty

### Calendar app version

4.5.0

### Browser

Chrome, Edge & Firefox

### Client operating system

Windows 11, Ubuntu 18.04.6

### Server operating system

Raspberry Pi , Container with Alpine Linux 3.18

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.0

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - cloud_py_api: 0.1.8
  - comments: 1.17.0
  - contacts: 5.4.0
  - contactsinteraction: 1.8.0
  - cookbook: 0.10.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.3.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mediadc: 0.3.6
  - memories: 5.4.1
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 4.3.2
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_saml: 5.2.2
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.15.0
  - files_external: 1.19.0
  - files_versions: 1.20.0 (installed 1.19.1)
  - geoblocker: 0.5.11 (installed 0.5.11)
  - password_policy: 1.17.0 (installed 1.16.0)
  - support: 1.10.0 (installed 1.9.0)
  - survey_client: 1.15.0 (installed 1.14.0)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.6.0)
```

**Comment by ChristophWurst** [comment]
do you see any errors in browser console/network or nextcloud.log?

**Comment by ralfbgithub** [comment]
no relevant entries in the nextcloud.log
Edge console: no errors but the warning: index.es.js:2337  Proxying an event bus of version 3.1.0 with 1.3.0

**Comment by naelfe** [comment]
I also updated to NC 27.1.0 and Calendar 4.5.0

(Updated the docker container https://github.com/linuxserver/docker-nextcloud which automatically updated the app as well)

My widget is not empty, but it has another issue:
For re-occuring events, it does not show when it will happen next, but when it was created- which makes it very confusing.
Same with the contact birthdays (yellow).

![image](https://github.com/nextcloud/calendar/assets/108142825/f6dec693-8091-48bf-bc71-548073cb27c8)
Blue = last day of the month
1st purple = every saturday, shown 1 time for the rest of month
2nd purple = regular event, no reoccurence
yellow = birthday
I do think they are sorted by the time they were created, but I am not sure.

when creating a new event for next week, I do get this:
![image](https://github.com/nextcloud/calendar/assets/108142825/270fd963-ba10-4344-8631-65e113a16d5f)
It has the right descriptive text to it (actual scheduled time, not when it was created) but it is displayed in last place, even though it is the first event to occur.

**Comment by ChristophWurst** [comment]
Talked to @st3iny. This is the same issue we had for mobile widget before: https://github.com/nextcloud/calendar/issues/4813. Bringing the mobile data to the browser via https://github.com/nextcloud/calendar/pull/5417 also gives us the bugs.

**Comment by miaulalala** [comment]
Needs improvement on the recurrence expansion as  discussed with @st3iny

**Comment by HyperCriSiS** [comment]
I have similar issues.
Since the calendar app and contacts app two days ago, both of them do not load anymore.
![waterfox_G8Wm3Zegzz](https://github.com/nextcloud/calendar/assets/11708192/2094f7f2-2315-4b2b-9e24-335e85d34666)
![waterfox_hzKTS2fyNE](https://github.com/nextcloud/calendar/assets/11708192/7895958f-7de0-4bb1-bd0b-c6542ea022cc)

Nothing related is in the logs.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/server/pull/40541?

**Comment by st3iny** [comment]
The issue fixed by @naelfe should be fixed by the linked issue (showing wrong dates/times). However, showing no event is a different issue I think.

Also note that there are more fixes regarding the ordering in https://github.com/nextcloud/calendar/pull/5486.

**Comment by MrShoenel** [comment]
I am running NC 27.1.2 and still have the empty widget issue. Should this fix here already be included or will it come in a future version of NC? If so, which one? Thanks!

**Comment by st3iny** [comment]
> I am running NC 27.1.2 and still have the empty widget issue. Should this fix here already be included or will it come in a future version of NC? If so, which one? Thanks!

It should be included in 27.1.2.

**Comment by ralfbgithub** [comment]
Widget is still empty with Nextcloud 27.1.2 and Calendar 4.5.2

**Comment by snagglewest** [comment]
Still not fixed after upgrading to 27.1.5 & calendar 4.6.0

**Comment by DeBaschdi** [comment]
still not fixed in NC 29.0.0

**Comment by zenhighzer** [comment]
same here.. in my calendar there are a lot of recurring and single items, but none of them are displayed in the dashboard

**Comment by Mace68** [comment]
I can't remember exactly when it started for me (I think in version 25.x.x) but I'm now on Nextcloud 28.0.6 and it hasn't worked for me in a very long time now. This has been an issue for lots of people for a very long time now. What other info can we provide to help solve this issue?

**Comment by estux** [comment]
As this is closed .... maybe it could be better to open another issue.

**Comment by ralfbgithub** [comment]
Fixed in 28.0.7 👍
