### ISSUE TITLE
New and updated appointments are not sent via e-mail

### ISSUE THREAD

**Issue by stoneubi** [nextcloud/calendar#5706]
### Steps to reproduce

1. Update NC to version 28.0.1
2. Update Calendar to Version 4.6.4
3. Login to NC and create a new calendar entry / appointment and invite some user or external attendee via e-mail

### Expected behavior

The newly created calendar entry should be sent via e-mail to the invited attendee. 

### Actual behaviour

No e-mail is sent. Also no e-mails are sent for changed calendar entries. 

Only if a newly created entry will be cancelled an e-mail with the cancellation is sent. 

Regardless if you create the calendar item directly in nextcloud calendar app or via DAVx5 or Thunderbird calendar, the result is the same. No e-mail with the invitation are sent any more. This worked create before the last update to calendar version 4.6.4.

### Calendar app version

4.6.4

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by Markoise** [comment]
I can understand the problem very well.
Especially if invited people have a GMail address.
Likewise, no emails will be sent if the appointment is created with an Android calendar app.
At least it works in the Nextcloud Calendar WebGUI as long as no GMail address is invited.

**Comment by stoneubi** [comment]
Any update on this issue!

**Comment by Alex13280815** [comment]
Same here, fresh install on Debian12, PHP 8.2, MariaDB, Apache, NC 28.0.2.

**Comment by grosjo** [comment]
Further to that, creating an event via CalDav (Davx here), does not trigger sending an email to the invited

**Comment by miaulalala** [comment]
Can you check your logs for any errors?
Can you also check your Mailer settings for your instance?

**Comment by Alex13280815** [comment]
Email Test is OK.
`
{"reqId":"F8eLKCjMNgK0nFnjSrzp","level":0,"time":"February 14, 2024 11:37:09","remoteAddr":"195.50.173.250","user":"--","app":"core","method":"GET","url":"/","message":"Remember-me token replaced","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"core","user":"Alex"}}
{"reqId":"F8eLKCjMNgK0nFnjSrzp","level":0,"time":"February 14, 2024 11:37:10","remoteAddr":"195.50.173.250","user":"--","app":"core","method":"GET","url":"/","message":"Session token replaced","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"core","user":"Alex"}}
{"reqId":"mC7K0EHPm7CKlKzV8r0B","level":0,"time":"February 14, 2024 11:37:12","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"ZNljCGowjKCfuDSwzLAj","level":0,"time":"February 14, 2024 11:37:12","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"ipcMiYXXJWv7WQqtbCFW","level":0,"time":"February 14, 2024 11:37:12","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"X1nVHN7xA6lvuWSbdemg","level":0,"time":"February 14, 2024 11:37:14","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"uo1LGBY9BcJtqgyDrxaS","level":0,"time":"February 14, 2024 11:37:14","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"mrbExwhNJaDdbPRaDNUY","level":0,"time":"February 14, 2024 11:37:24","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/remote.php/dav/calendars/Alex/persnlich-1/845CE87E-7CEA-4947-A049-778EEAB1F4E3.ics","message":"Activity generated for new calendar object in calendar 2","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav"}}
{"reqId":"mrbExwhNJaDdbPRaDNUY","level":0,"time":"February 14, 2024 11:37:24","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/remote.php/dav/calendars/Alex/persnlich-1/845CE87E-7CEA-4947-A049-778EEAB1F4E3.ics","message":"Reminders of calendar object of calendar 2 created","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 2","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\FilesReminders\\BackgroundJob\\ScheduledNotifications job with ID 2","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\FilesReminders\\BackgroundJob\\ScheduledNotifications job with ID 2 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 3","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 4","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 5","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 7","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 9","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 10","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 12","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 13","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 14","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 16","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 17","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 18","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 19","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 19","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Notifications\\BackgroundJob\\SendNotificationMails job with ID 19 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 21","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 23","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 24","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 24","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 24 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 26","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 27","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 28","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 29","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 30","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files\\BackgroundJob\\CleanupDirectEditingTokens job with ID 30","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files\\BackgroundJob\\CleanupDirectEditingTokens job with ID 30 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 35","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Circles\\Cron\\Maintenance job with ID 35","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"","method":"","url":"--","message":"[debug] running maintenance (1)","userAgent":"--","version":"28.0.2.5","data":{"app":""}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Circles\\Cron\\Maintenance job with ID 35 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 37","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Log\\Rotate job with ID 37","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Log\\Rotate job with ID 37 in 0 seconds","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 38","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 39","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 57","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 58","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 129","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 138","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"zrKWbaD8a1UTLbvkgxAX","level":0,"time":"February 14, 2024 11:40:01","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 141","userAgent":"--","version":"28.0.2.5","data":{"app":"cron"}}
{"reqId":"kYdxnDUiDVFz6jH7zbh5","level":0,"time":"February 14, 2024 11:42:15","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"EWlkhpl0jHQsNeaCfN5B","level":0,"time":"February 14, 2024 11:43:57","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"zpEiwlumDWbJdB5kplkz","level":0,"time":"February 14, 2024 11:44:02","remoteAddr":"195.50.173.250","user":"Alex","app":"PHP","method":"GET","url":"/index.php/settings/admin/overview","message":"Creation of dynamic property OCA\\FirstRunWizard\\Settings\\Personal::$urlGenerator is deprecated at /var/www/nextcloud/apps/firstrunwizard/lib/Settings/Personal.php#40","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"SUrewTRsPhVfeMSjv3TI","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"DhPgIcsBKrDjBwMzN1ie","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"IXPPdIwK1LK6mwBruxU2","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/.well-known/nodeinfo","message":"3 well known handlers registered","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"5QX2bQKrEV3KYdoGE5jW","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/.well-known/webfinger","message":"3 well known handlers registered","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\DAV\\SetupChecks\\NeedsSystemAddressBookSync","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\LogReader\\SetupChecks\\LogErrors","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Notifications\\Settings\\SetupWarningOnRateLimitReached","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\AppDirsWithDifferentOwner","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\BruteForceThrottler","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\CheckUserCertificates","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\CodeIntegrity","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\CronErrors","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\CronInfo","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingColumns","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingIndices","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:03","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabaseHasMissingPrimaryKeys","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DatabasePendingBigIntConversions","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\DefaultPhoneRegionSet","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\EmailTestSuccessful","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\FileLocking","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\ForwardedForHeaders","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\InternetConnectivity","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\JavaScriptModules","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\LegacySSEKeyFormat","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\MaintenanceWindowStart","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\MemcacheConfigured","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\OverwriteCliUrl","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpDefaultCharset","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpFreetypeSupport","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpGetEnv","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpMemoryLimit","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpModules","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOpcacheSetup","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutdated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutputBuffering","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\RandomnessSecure","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\ReadOnlyConfig","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SupportedDatabase","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SystemIs64bit","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\TransactionIsolation","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"tqArMLnJkT99rWVBAcGr","level":0,"time":"February 14, 2024 11:44:04","remoteAddr":"195.50.173.250","user":"Alex","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Theming\\SetupChecks\\PhpImagickModule","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
{"reqId":"oqKmIh2oi0ciTj09JvCQ","level":0,"time":"February 14, 2024 11:44:09","remoteAddr":"195.50.173.250","user":"Alex","app":"PHP","method":"GET","url":"/index.php/settings/admin/logging","message":"Creation of dynamic property OCA\\FirstRunWizard\\Settings\\Personal::$urlGenerator is deprecated at /var/www/nextcloud/apps/firstrunwizard/lib/Settings/Personal.php#40","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"GBGvNlRLHnc0c8QrGira","level":0,"time":"February 14, 2024 11:44:09","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"PUT","url":"/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
{"reqId":"NNliKDkCvUSoAaImFrKY","level":0,"time":"February 14, 2024 11:44:09","remoteAddr":"195.50.173.250","user":"Alex","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"Found 1 applicable event(s), changing user status","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"dav","user":"Alex"}}
`

**Comment by miaulalala** [comment]
Nothing in the logs. Can you enable debug mode and try again?

**Comment by stoneubi** [comment]
Today I downloaded Google Calendar on my Android device and I created a new appointment with invited attendees and nextcloud calendar sent the expected invitations through email. If I do the same things in my Android calendar app called fossify calendar 1.0.2 (new version of simple calendar app) and start Davx5 to synchronize with my nextcloud, no invitations will be sent. Very strange.

**Comment by stoneubi** [comment]
As I can see, a new version of Davx5 will be released with the next hours. Version davx5-ose-4.3.13-ose-release.apk.

As Google calendar works maybe this bug is linked to Davx5?

On the other hand the invitations are also not sent if the calendar entry has been created directly in nextcloud itself.

**Comment by Alex13280815** [comment]
> Nothing in the logs. Can you enable debug mode and try again?

[nextcloud (2).log](https://github.com/nextcloud/calendar/files/14292104/nextcloud.2.log)
I give my best. :-)

**Comment by grosjo** [comment]
This is really a critical bug for a calendar not to sent invites.

How can I help ?

**Comment by miaulalala** [comment]
I can't reproduce - invitations get sent. Is there anything special about the attendee email addresses? I've tried with both other users and external attendees and the emails get sent.

Are the calendar you're trying to invite someone to special? Calendars that have been shared / are shared with you?

**Comment by Markoise** [comment]
Since Nextcloud 28.0.3 the emails have been sent again.

But it still remains unpleasant with Gmail addresses.
If you send an appointment to a GMail address, the person can accept the appointment using the Nextcloud "Accept" link, but it will not be recorded as accepted in the calendar. Changes to appointments are entered as a new appointment.
But that's probably a Google problem, right?

Equally problematic:
If I receive an invitation (in K9 email) I cannot accept the appointment. Even in the Nextcloud Mail app, appointments cannot be entered in the calendar.

Calendars can now be subscribed to again.

Thank you!!

**Comment by miaulalala** [comment]
> but it will not be recorded as accepted in the calendar.

you mean in the associated gmail calendar?
No, it will not as the link leads to the nextcloud instance which is not connected to google calendar.

For any invitation you accept via link, if you don't use the integrated iMIP service (native accept/decline buttons in your clients) only the nextcloud instance calendar will be updated; unless you have an email address that is associated with a calendar principal on this nextcloud instance, then it will work. That is just how the protocol works.

**Comment by Markoise** [comment]
I mean that the person otherwise has no opportunity to accept the appointment.
Any appointment request from another calendar provider can be accepted using GMail and added to Google Calendar.

Unfortunately, there is no appointment request from the Nextcloud calendar. Only the ICS attachments.

Now I'm not sure whether this is a Google problem or a Nextcloud problem.

**Comment by Markoise** [comment]
Sometimes emails are sent, sometimes not.

**Comment by miaulalala** [comment]
Can you tell me step by step what happens?

So:
1. Create calendar event in Nextcloud
2. Invite someone with a gmail address
3. ???

and what you expect to happen, too? Maybe I can get a clearer picture what you're looking for and where the issue is.

**Comment by Markoise** [comment]
**Steps for new appointment:**

1. Create an appointment in the NC calendar (also ETAR, Google Calendar app).
2. Invite participants name@gmail.com
3. Sometimes an email is sent, sometimes not.

**Steps for changing an appointment:**

1. Change the appointment in the NC calendar (also ETAR, Google Calendar app).
2. Sometimes an email is sent, sometimes not.

When an email is sent, there are 1 - 2 .ICS files attached. The invitee's different mail client (Gmail App, K-9) sometimes interprets the invitation as such and offers "accept" / "reject". But sometimes not.

**Expectation:**
name@gmail.com receives an email with an appointment invitation, which can be responded to with “accept” or “reject”.

**Comment by miaulalala** [comment]
Can you tell me if you use Ajax Cron, WebCron or Cron? You can find that in your admin settings in "Basic Settings".

**Comment by Markoise** [comment]
![grafik](https://github.com/nextcloud/calendar/assets/64073726/64d6a622-2288-4591-986f-6a22e6578ad1)

I'm using CRON as recommended

**Comment by miaulalala** [comment]
> **Steps for changing an appointment:**
> 
>     1. Change the appointment in the NC calendar (also ETAR, Google Calendar app).
> 
>     2. Sometimes an email is sent, sometimes not.

The second one __might__ be down to what changed about the event (let's please call them events, appointments are another feature of the calendar app and it confuses me :sweat_smile: ). There's something called a "significant change" in calendaring, so if you only changed the title of an event, that is not enough to trigger an update email. If you change the date and / or time, that is.

Are there any special chars in those gmail email addresses you're sending too? Might be related to https://github.com/nextcloud/calendar/issues/2149

**Comment by Markoise** [comment]
Ok, I understand. I have now tried again.

1. created an event in the NC calendar
2. invited name@gmail.com
3. an invitation arrived, which I was able to accept
4. moved the event in the NC calendar to another time
5. an update arrived and could be accepted
6. renamed event in the NC calendar
7. event will not be renamed for someone else
8. location in the appointment changed
9. the location is not changed for another person
10. event moved again.
11. the appointment update was sent with a new name and could be accepted.

Unfortunately, it is not good that points 6 and 8 are not updated for the invited persons. This is because when a renamed event is canceled, it is not removed from the calendar.

The K9 Mail app does not recognize the invitation as an event. The GoogleMail app, on the other hand, does.

I don't know why it suddenly works now, but there was a recent update to the NC calendar. 🤷‍♂️

I will continue to monitor this. Maybe I can switch to Nextcloud completely soon.

Translated with DeepL.com (free version)

**Comment by Markoise** [comment]
It seems that mail is only sent when you create an event in the NC calendar. But not in an Android app like ETAR or the Google Calendar app.

**Comment by miaulalala** [comment]
> It seems that mail is only sent when you create an event in the NC calendar. But not in an Android app like ETAR or the Google Calendar app.

How did you connect your Nextcloud Calendar to your Google Calendar App? Same for ETAR (although Ive never used that one myself).

As for the significant changes, the RFC defines the following properties that trigger a significant change:
```
"DTSTART"
"DTEND"
"DUE"
"RDATE"
"RRULE"
"EXDATE"
"EXRULE"
"STATUS"
```
The location is a CAN but not a MUST for the event. It's definitely worth a discussion if that should trigger an event.

**Comment by Markoise** [comment]
I have DAVx5 installed on my smartphone, which allows me to see and edit the calendars in Google Calendar and ETAR.

I think it would be good if the change of location triggered information. It is equally important if the title of the event and a comment are changed.

This is also the case with standard calendars (Outlook/Exchange, Google Calendar, etc.).

**Comment by Markoise** [comment]
I need to make a correction.

1. create event in the NC calendar and invite name@gmail.com
2. event invitation is sent and accepted
3. event is moved to another time in the NC calendar
4. event update is sent to name@gmail.com.
5. event update is accepted
6. event is still displayed in the Google calendar at the old time

This means that the event update is not forwarded correctly.

I suggest you try this out for yourself. You will see that it does not work correctly.

**Comment by Markoise** [comment]
> is this a NC calendar that was added to google with DavX5? Or is it a Google calendar?

No, this is the event that was created by the invitation in Google Calendar.
Or what do you mean exactly?

**Comment by miaulalala** [comment]
You updated an event. You accepted an event. Which calendar did you store the accepted event in - a calendar created and managed by Google Calendar, or a calendar created and managed by Nextcloud that is accessible for you on your phone via DavX5.

**Comment by Markoise** [comment]
The accepted event is in someone else's Google Calendar.

I think it has to do with when the content of an appointment is changed. If the title, location and/or description changes and then the time, it no longer works.

The same happens when someone else sends me an event. Postponements are implemented, but if the content of the event changes, the error also occurs there.

**Comment by miaulalala** [comment]
> The accepted event is in someone else's Google Calendar.
> 
> I think it has to do with when the content of an appointment is changed. If the title, location and/or description changes and then the time, it no longer works.
> 
> The same happens when someone else sends me an event. Postponements are implemented, but if the content of the event changes, the error also occurs there.

But the one that is supposed to do the updating is Google Calendar, right? If so there's nothing we can do about that.

**Comment by Markoise** [comment]
No. The changes are made in the Nextcloud calendar. 
This is also where I created the event. 
I suspect that if the event title and/or location is changed, no more emails will be sent.

At least that's how it looks.

**Comment by miaulalala** [comment]
Possibly related to https://github.com/nextcloud/server/issues/41084

**Comment by rcwschaller** [comment]
There are (at least) two separate issues discussed here:
- event updates not getting sent by mail: there was a bug fixed in nextcloud/server#41084, please evaluate again if you can still reproduce after your instance receives the update.
- event initial creations not being sent by mail: As far as I can tell, this would be unrelated to the issue 41084.

I believe this discussion would greatly benefit if we would have ICS files of the events (exported from nextcloud or from the email attachments) for the steps of the reproduction section where it worked or did not work as expected.

**Comment by Markoise** [comment]
I would have an ICS file. Initially I was able to invite a GMail contact to it. It was also possible to reschedule an appointment. If I now postpone this appointment, no notification is sent.

I have only "renamed" the email addresses because I don't want these addresses to be public. 

If you look at the file in an editor, you will notice that the mail address is wrapped in line 38. I don't know whether this plays a role or is related to the export from the NC calendar.

[termin_export.zip](https://github.com/nextcloud/calendar/files/14760679/termin_export.zip)

**Comment by stoneubi** [comment]
Can you please let me know how I can generate ics files using Android device with Google calendar app and davx5.

So I can compare the non working ics with the working ics files.

Thank you
Stoneubi

**Comment by Markoise** [comment]
> Can you please let me know how I can generate ics files using Android device with Google calendar app and davx5.
> 
> So I can compare the non working ics with the working ics files.
> 
> Thank you Stoneubi

You can click here in your Nextcloud Calendar to export this event.

![grafik](https://github.com/nextcloud/calendar/assets/64073726/2336c2b1-d52b-4e63-8287-8bca974f5e28)

**Comment by stoneubi** [comment]
Ok, I will create two same events and will compare the ics files.

To my understanding I think Google calendar app on Android and e.g. fossify calendar app on Android are creating the events in a different way. As mentioned, events created with Google calendar app causes nc calendar do send the email invitation. So I wonder if for debug reasons the log level from davx5 my show different data for the same calendar event.

**Comment by stoneubi** [comment]
Here are my results - I created two same events on my android smartphone with two different apps. 

Google Calendar app on android device -> the inviation e-mail was sent:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.3.15-ose ical4j/3.2.14 (com.google.android.calendar)
BEGIN:VTIMEZONE
TZID:Europe/Vienna
LAST-MODIFIED:20230104T023643Z
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20240326T190233Z
UID:5acc825f-f527-415a-bd68-09b7468cbcb7
SUMMARY:Test created in Google calendar app on Android
DTSTART;TZID=Europe/Vienna:20240407T130000
DTEND;TZID=Europe/Vienna:20240407T140000
ORGANIZER:mailto:my-email-adress@yyyyyyyy.com
ATTENDEE;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:invited_person@yyyyyyyy.com
ATTENDEE;RSVP=TRUE;CN=Kalender;PARTSTAT=ACCEPTED:mailto:my-email-adress@yyyyyyy
 y.com
END:VEVENT
END:VCALENDAR

fossify calendar app on android -> no inviation e-email was sent:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:DAVx5/4.3.15-ose ical4j/3.2.14 (org.fossify.calendar)
BEGIN:VTIMEZONE
TZID:Europe/Vienna
LAST-MODIFIED:20230104T023643Z
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20240326T190054Z
UID:df3cc969-67d3-4995-b966-9ae5297774d5
SUMMARY:Test created in fossify calendar app on Android
DTSTART;TZID=Europe/Vienna:20240407T130000
DTEND;TZID=Europe/Vienna:20240407T140000
STATUS:CONFIRMED
ORGANIZER:mailto:my-email-adress@yyyyyyyy.com
ATTENDEE;RSVP=TRUE;CUTYPE=UNKNOWN;PARTSTAT=NEEDS-ACTION;SCHEDULE-STATUS=1.0
 :mailto:invited_person@yyyyyyyy.com
END:VEVENT
END:VCALENDAR

Differences: 

<html>
<head>
<style>
p.Normal
{margin:0.0pt;
margin-top:0.0pt;
margin-bottom:0.0pt;
margin-left:0.0pt;
margin-right:0.0pt;
text-indent:0.0pt;
font-family:"Basic Sans";
font-size:10.0pt;
color:Black;
font-weight:normal;
}

</style>
</head>
<body>

BEGIN:VCALENDAR | BEGIN:VCALENDAR
-- | --
VERSION:2.0 | VERSION:2.0
PRODID:DAVx5/4.3.15-ose ical4j/3.2.14 (org.fossify.calendar) | PRODID:DAVx5/4.3.15-ose ical4j/3.2.14 (com.google.android.calendar)
BEGIN:VTIMEZONE | BEGIN:VTIMEZONE
TZID:Europe/Vienna | TZID:Europe/Vienna
LAST-MODIFIED:20230104T023643Z | LAST-MODIFIED:20230104T023643Z
BEGIN:DAYLIGHT | BEGIN:DAYLIGHT
TZNAME:CEST | TZNAME:CEST
TZOFFSETFROM:+0100 | TZOFFSETFROM:+0100
TZOFFSETTO:+0200 | TZOFFSETTO:+0200
DTSTART:19810329T020000 | DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU | RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT | END:DAYLIGHT
BEGIN:STANDARD | BEGIN:STANDARD
TZNAME:CET | TZNAME:CET
TZOFFSETFROM:+0200 | TZOFFSETFROM:+0200
TZOFFSETTO:+0100 | TZOFFSETTO:+0100
DTSTART:19961027T030000 | DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU | RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD | END:STANDARD
END:VTIMEZONE | END:VTIMEZONE
BEGIN:VEVENT | BEGIN:VEVENT
DTSTAMP:20240326T190054Z | DTSTAMP:20240326T190233Z
UID:df3cc969-67d3-4995-b966-9ae5297774d5 | UID:5acc825f-f527-415a-bd68-09b7468cbcb7
SUMMARY:Test created in fossify calendar app on Android | SUMMARY:Test created in Google calendar app on Android
DTSTART;TZID=Europe/Vienna:20240407T130000 | DTSTART;TZID=Europe/Vienna:20240407T130000
DTEND;TZID=Europe/Vienna:20240407T140000 | DTEND;TZID=Europe/Vienna:20240407T140000
STATUS:CONFIRMED | ORGANIZER:mailto:my-email-adress@yyyyyyyy.com
ORGANIZER:mailto:my-email-adress@yyyyyyyy.com | ATTENDEE;RSVP=TRUE;SCHEDULE-STATUS=1.1:mailto:invited_person@yyyyyyyy.com
ATTENDEE;RSVP=TRUE;CUTYPE=UNKNOWN;PARTSTAT=NEEDS-ACTION;SCHEDULE-STATUS=1.0 | ATTENDEE;RSVP=TRUE;CN=Kalender;PARTSTAT=ACCEPTED:mailto:my-email-adress@yyyyyyy
:mailto:invited_person@yyyyyyyy.com | y.com
END:VEVENT | END:VEVENT
END:VCALENDAR | END:VCALENDAR


</body>
</html>

**Comment by rcwschaller** [comment]
Only regarding relation to issue #41084:
- Example by @Markoise: This is a SEQUENCE=10 iteration of this event. Although it not clear to me, if this is the ICS before or after the update which does not sent out the email, it is safe to say, that it is unrelated to issue 41084 as both 9->10 and 10->11 would still trigger an email with the pre-bugfix code as long as it is an update to e.g. the starting time.
- Examples by @stoneubi: Both of his examples are event creations, which - as mentioned earlier - are entirely unrelated to the bugfix in issue 41084.

Sorry that I can't be more of a help here.

**Comment by flortsch** [comment]
I debugged the Nextcloud code and I think it's a bug in the Fossify calendar app. Nextcloud thinks that the invited attendee is a room or resource, due to `CUTYPE` being set to `UNKNOWN`. And I think this is passed from the Fossify calendar app. See attached screenshots from the debugging.

![Bildschirmfoto vom 2024-03-28 09-06-48](https://github.com/nextcloud/calendar/assets/15350076/78f4b937-8ba0-4349-b864-a8a2c2651f67)
![Bildschirmfoto vom 2024-03-28 09-05-50](https://github.com/nextcloud/calendar/assets/15350076/4f6b80bd-4eee-4659-bf07-9d67c77d297c)

**Comment by flortsch** [comment]
Question to Nextcloud devs: is this expected behavior or is the Nextcloud check `isRoomOrResource` maybe too strict for `CUTYPE=UNKNOWN` and should the check be more relaxed?

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/server/pull/40876. Maybe we could remove `UNKNOWN` from here @miaulalala, unless there's specific cases with `UNKNOWN` `CUTYPES`s we need to exclude?

**Comment by flortsch** [comment]
Found a second check on the `UNKNOWN` `CUTYPE` here: https://github.com/nextcloud/server/blob/7dad12ef75856c1f73cf744f7c154da20d019498/apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php#L257.

It's unrelated to this issue here but might result in other notification emails not being sent for this `CUTYPE`.

**Comment by miaulalala** [comment]
> See [nextcloud/server#40876](https://github.com/nextcloud/server/pull/40876). Maybe we could remove `UNKNOWN` from here @miaulalala, unless there's specific cases with `UNKNOWN` `CUTYPES`s we need to exclude?

Yeah we could, that would be fine I think.

**Comment by stoneubi** [comment]
Hi,

I upgraded to version 29.0.1. and I happy to report that this bug is fixed in my setup - Android phone, fossify calendar, davx5 sync to nextcloud.

Thank you very much 👍😊
Stoneubi

**Comment by Markoise** [comment]
Funny. I still have the same problem with the Fossify Calendar. But otherwise it looks really good now. 

Unfortunately, I can't accept appointment confirmations with K9 Mail, but that's probably due to K9 Mail.

**Comment by stoneubi** [comment]
I also use k9 and in the invitation email there is the ics file and a link to the online nextcloud invitation answer form.

K9 cannot handle ics files and I also have to use the link button. 

But if I open the same email in outlook I can accept or decline directly in the email / calendar invitation.

**Comment by Markoise** [comment]
> 
> But if I open the same email in outlook I can accept or decline directly in the email / calendar invitation.
>
Yes, it now works without any problems with Outlook, emClient, FairEmail.

Thanks for that!

**Comment by stoneubi** [comment]
This issue came back since last update. Events created with Android fossify app won't send email invitations. Updated and cancelled events so send emails.

**Comment by bb4242** [comment]
> This issue came back since last update. Events created with Android fossify app won't send email invitations. Updated and cancelled events so send emails.

It looks like the fix for this issue (https://github.com/nextcloud/server/pull/44938) was reverted in https://github.com/nextcloud/server/pull/45547, which was released in [v30.0.0](https://github.com/nextcloud/server/releases/tag/v30.0.0).

The fix simply removed the `UNKNOWN` type from a check in the function `isRoomOrResource` (see [here](https://github.com/nextcloud/server/blob/a28f2647837913eacab31c3fac2b943ab8ee9131/apps/dav/lib/CalDAV/Schedule/IMipService.php#L685)) but https://github.com/nextcloud/server/commit/43ee9488905bef91ed9be3057afcfb4c912d3450 [added it back in](https://github.com/nextcloud/server/blob/43ee9488905bef91ed9be3057afcfb4c912d3450/apps/dav/lib/CalDAV/Schedule/IMipService.php#L887). I'm not sure if the reversion was intentional or not.

Tagging @miaulalala and @SebastianKrupinski as the author of the fix and the subsequent commit, respectively.
