### ISSUE TITLE
Nextcloud 28 and 29: Change of view (week, month...) is not memorized

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/calendar#6131]
### Steps to reproduce

1. Go to your calendar (which may be in monthly or weekly view, for example)
2. Switch to another view, i.e. monthly view if you're in weekly view, or vice versa.
3. Click on the Calendar app icon at the very top of the interface, and see that you're still in the previous view.

I've found that if you switch views a second time before clicking on the Calendar app icon, the display is switched correctly. To be checked. 

The problem is not necessarily easy to reproduce. Take the time to watch the video too.

[Capture vidéo du 09-07-2024 16:50:23.webm](https://github.com/nextcloud/calendar/assets/33763786/8544322f-0f83-4dab-a20e-0333b8ebf4c9)

### Expected behavior

The change of view should remain after clicking on the Calendar app icon at the very top.

### Actual behaviour

Previous view mode remains.

### Calendar app version

4.7.10

### CalDAV-clients used

N/A

### Browser

FF 126.0.2

### Client operating system

Ubuntu 22.04 LTS

### Server operating system

CentOS

### Web server

Nginx

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

29.0.1

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc29.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "29.0.1.1",
    "overwrite.cli.url": "https:\/\/nc29.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc29.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 2,
        "timeout": 0
    },
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "updater.release.channel": "beta",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v1",
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "admin_audit",
        "user_ldap",
        "onlyoffice",
        "groupfolders"
    ],
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance_window_start": 1,
    "maintenance": false
}
```

### Nextcloud configuration

```Text
Enabled:
 - activity: 2.21.1
 - admin_audit: 1.19.0
 - assistant: 1.0.9
 - calendar: 4.7.10
 - call_summary_bot: 1.1.0
 - circles: 29.0.0-dev
 - cloud_federation_api: 1.12.0
 - collectives: 2.10.1
 - comments: 1.19.0
 - contacts: 6.0.0
 - contactsinteraction: 1.10.0
 - context_chat: 2.1.2
 - dashboard: 7.9.0
 - dav: 1.30.1
 - deck: 1.13.0
 - federatedfilesharing: 1.19.0
 - federation: 1.19.0
 - files: 2.1.0
 - files_downloadlimit: 2.0.0
 - files_pdfviewer: 2.10.0
 - files_reminders: 1.2.0
 - files_sharing: 1.21.0
 - files_trashbin: 1.19.0
 - files_versions: 1.22.0
 - firstrunwizard: 2.18.0
 - forms: 4.2.3
 - groupfolders: 16.0.6
 - impersonate: 1.16.0
 - integration_openai: 2.0.1
 - integration_replicate: 3.0.0
 - logreader: 2.14.0
 - lookup_server_connector: 1.17.0
 - mail: 3.6.0
 - nextcloud_announcements: 1.18.0
 - notifications: 2.17.0
 - oauth2: 1.17.0
 - onlyoffice: 9.2.0
 - password_policy: 1.19.0
 - photos: 2.5.0
 - privacy: 1.13.0
 - provisioning_api: 1.19.0
 - recommendations: 2.1.0
 - related_resources: 1.4.0
 - richdocuments: 8.4.2
 - serverinfo: 1.19.0
 - settings: 1.12.0
 - sharebymail: 1.19.0
 - spreed: 19.0.0
 - support: 1.12.0
 - systemtags: 1.19.0
 - tables: 0.7.2
 - text: 3.10.0
 - theming: 2.4.0
 - twofactor_backupcodes: 1.18.0
 - updatenotification: 1.19.1
 - user_ldap: 1.20.0
 - user_status: 1.9.0
 - viewer: 2.3.0
 - weather_status: 1.9.0
 - workflowengine: 2.11.0
 - workspace: 3.2.0
Disabled:
 - app_api: 2.6.0
 - bruteforcesettings
 - encryption
 - files_external
 - survey_client: 1.17.0
 - suspicious_login
 - twofactor_totp
```

### Web server error log

```Text
Can be provided if necessary
```

### Log file

```Text
Can be provided if necessary
```

### Browser log

```Text
Can be provided if necessary
```

### Additional info

Can be provided if necessary

**Comment by tcitworld** [comment]
Are you sure about the app version? This suspiciously looks like https://github.com/nextcloud/calendar/issues/6076#issuecomment-2200458740 which was fixed in https://github.com/nextcloud/calendar/pull/6103

**Comment by Jerome-Herbinet** [comment]
> Are you sure about the app version? This suspiciously looks like [#6076 (comment)](https://github.com/nextcloud/calendar/issues/6076#issuecomment-2200458740) which was fixed in #6103

Yes, I'm sure ; I'll test it again in 2 weeks (after my holidays), by the way.

**Comment by Jerome-Herbinet** [comment]
@tcitworld Just tested Nextcloud 31.0.2 with Calendar 5.2.0, and it still occurs.

https://github.com/user-attachments/assets/e8dbd404-aeeb-46be-b1b8-2394ca839381

**Comment by Jerome-Herbinet** [comment]
In my opinion, this behaviour is problematic.

Or, if it is a feature (and not a bug), there should be new options in the settings:
- default display (choice between weekly, monthly views, etc.)
- display the default view mentioned above each time the page loads, or the last display mode selected in the interface

**Comment by ChristophWurst** [comment]
Can't reproduce. It works for me.

Do you see a `POST apps/calendar/v1/config/view`? The new preference isn't stored immediately. You have to stay on that view for ~10s.

**Comment by Jerome-Herbinet** [comment]
> Can't reproduce. It works for me.
> 
> Do you see a `POST apps/calendar/v1/config/view`? The new preference isn't stored immediately. You have to stay on that view for ~10s.

@ChristophWurst Indeed, if you wait about 10 seconds, the selected view is saved... but for ordinary users, this is a real UX problem (even I'm familiar with Nextcloud, I did not understand this mechanism on my own...).
