### ISSUE TITLE
The day Until automatically jumps to the next day

### ISSUE THREAD

**Issue by gnetworks-maker** [nextcloud/calendar#7317]
### Steps to reproduce

As soon as you create a calendar entry starting at 7:00 or 8:00, the to-date jumps to the next day. Calendar entries starting at 9:00 remain on the same day.

### Expected behavior

The to-date should also remain on the same day for these times

### Actual behavior

The to-date jumps to the next day

### Calendar app version

5.5.1

### Browser

Chrome 139.0.7258.155

### Client operating system

Win10

### Server operating system

Debian

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Nextcloud version

Nextcloud Hub 10 (31.0.8)

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

**Comment by Auren-Frost** [comment]
I am also experiencing this issue on version 31.0.7. 

It sometimes has trouble correcting even after I manually set the date back one day as well. Hopefully this is resolved soon.

**Comment by SebastianKrupinski** [comment]
Hi @gnetworks-maker 

Can you update to the most recent version and let us know if the issue still exists.

**Comment by gnetworks-maker** [comment]
Hi @SebastianKrupinski 

Updated to Calendar 5.5.5 on Nextcloud 31.0.9 and the issue is still exists.

Regards

![Image](https://github.com/user-attachments/assets/4fe0a34c-9c1a-4497-b46e-f2fcdeece474)
