### ISSUE TITLE
[beta 6] js api

### ISSUE THREAD

**Issue by CorentinS6** [nextcloud/calendar#7359]
### Steps to reproduce

1. load calendar app

### Expected behavior

- no js error,
- meeting proposal working

### Actual behavior

- js error on page load
- nothing happend on click to add new metteing proposal

### Calendar app version

6.0.0-rc1

### Browser

firefox 140.1.0esr (64 bits)

### Server operating system

Ubuntu 25.04

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

32.0.0-rc1

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text
Avertissements Content-Security-Policy 2
[INFO] calendar: 
Initial settings:
	- AppVersion: 6.0.0-rc.1
	- EventLimit: true
	- FirstRun: true
	- ShowWeekNumbers: true
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: false
	- SlotDuration: 00:30:00
	- DefaultReminder: none
	- TalkEnabled: true
	- TasksEnabled: true
	- TasksSidebar: false
	- Timezone: automatic
	- HideEventExport: false
	- ForceEventAlarmType: false
	- disableAppointments: false
	- CanSubscribeLink: true
	- attachmentsFolder: /Calendar
	- ShowResources: true
	- PublicCalendars: 
 
Object { app: "calendar", uid: "---", level: 0 }
calendar-main.js:2:2666857
Calendar API not initialized calendar-main.js:2:5577658
    calendarSpanDays ProposalEditor.vue:487
    VueJS 5
[INFO] core: session heartbeat polling started 
Object { app: "core", uid: "---", level: 0 }
core-common.js:1:2207202
[INFO] calendar: Updated moment locale: fr 
Object { app: "calendar", uid: "---", level: 0 }
calendar-main.js:2:2666857
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:1:344607
calendar home scanned 
Array(3) [ {…}, {…}, {…} ]
 
Array [ {…} ]
 
Array []
calendar-main.js:2:98471
Uncaught (in promise) Error: 
    y index.mjs:589
    C index.mjs:595
    request index.mjs:851
    propFind index.mjs:766
    findAll index.mjs:1313
    findAllByFilter index.mjs:1323
    findAllCalendars index.mjs:2258
    p caldavService.js:66
    backgroundSyncJob Calendar.vue:267
calendar-main.js:2:2375488
Slowing down notifications: Status 500 NotificationsApp-BnrwwvOH.chunk.mjs:84:57148
```

**Comment by CorentinS6** [comment]
same problem with 6.0.0-rc2 (firefox 128.10.0esr (64 bits))

> Calendar API not initialized ProposalEditor.vue:487

works on chromium

**Comment by SebastianKrupinski** [comment]
> same problem with 6.0.0-rc2 (firefox 128.10.0esr (64 bits))
> 
> > Calendar API not initialized ProposalEditor.vue:487
> 
> works on chromium

Hi, thank you for bringing this to our attention, that's odd that there is a issue with Firefox, as I wrote the entire proposals feature in firefox.

Have you tried clearing the browser cache? Dev Tools -> Network Tab -> Disable Cache, then reload the page.

**Comment by CorentinS6** [comment]
Hi,
First of all, tanks a lot for your work on this great feature !
Same result with this tips :( . I've tried private nav', but this bug in JS remain.

<img width="1916" height="504" alt="Image" src="https://github.com/user-attachments/assets/74db6ac3-88e5-4ee7-b3f1-32f61b443783" />

**Comment by SebastianKrupinski** [comment]
> Hi, First of all, tanks a lot for your work on this great feature ! Same result with this tips :( . I've tried private nav', but this bug in JS remain.

Thank you, we are glad you like the feature. There are a few more improvements coming to it soon.

Okay, with the screen shot you attached, gives me a good idea of where the issue is, just odd that it is not happening for me.

**Comment by SebastianKrupinski** [comment]
@CorentinS6 

I had a look in to this, yes there is a error in the browser log, because we log the fact the api is not available yet. But this should not prevent the feature from working, as it is not actually an error but only console output.

Are there any other errors?

**Comment by CorentinS6** [comment]
Hello,
Yep, the problem is, when i lick to add new meeting proposal. Nothing happend.
1. in js log, a prodind is send
2. UI is freezing, and this alert comes few seconds later : 
<img width="840" height="65" alt="Image" src="https://github.com/user-attachments/assets/2b782b4b-17de-48b3-960f-3733b7d82cd6" />
3. if i click on "Debug", i get this screen :
<img width="1912" height="376" alt="Image" src="https://github.com/user-attachments/assets/0701147d-5a55-4709-865c-0f46adc41ca8" />

**Comment by SebastianKrupinski** [comment]
Going to close this ticket as it seems the error is solved.

**Comment by melroy89** [comment]
I also still see this error:

```
Calendar API not initialized ProposalEditor.vue:485
    calendarSpanDays ProposalEditor.vue:485
    VueJS 8
    confirmTransition vue-router.esm.js:2404
    a vue-router.esm.js:2084
    a vue-router.esm.js:2091
    De vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    a vue-router.esm.js:2084
    a vue-router.esm.js:2088
    m vue-router.esm.js:2384
    ke vue-router.esm.js:2162
    m vue-router.esm.js:2362
    a vue-router.esm.js:2087
    a vue-router.esm.js:2091
    De vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    init vue-router.esm.js:2996
    beforeCreate vue-router.esm.js:1298
    VueJS 4
    <anonymous> main.js:53
    <anonymous> main.js:63
    <anonymous> main.js:63
```

Using Calendar version 6.0.1
