### ISSUE TITLE
email notification after data event update, not only dates

### ISSUE THREAD

**Issue by paco-salvador** [nextcloud/calendar#848]
### Steps to reproduce
1.Create an event 
2. add attendants
3. modify title, matter ...

### Expected behaviour
Attendants receive an email with the event update

### Actual behaviour
only receive email if change date or time

### Server configuration

**Operating system**: Debian

**Web server:**

**Database:** Mariadb 10.1.29

**PHP version:** 7.0.27

**Server version:** 13.0.4

**Calendar version:** 1.6.1

**Updated from an older installed version **

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Be sure to replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CalDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by georgehrke** [comment]
The event summary is generally not considered a significant change: http://tools.ietf.org/html/rfc5546#section-2.1.4

In what way would you change the title so it jeopardize the attendance of others?

**Comment by paco-salvador** [comment]
By now I was using outlook with caldav sync to connect to my  nextcloud calendar, the meeting is not  really a meeting, I use it like a task, and the attenders review if the work is done or not, and to inform about it I used to change the title event.

Now I 'm using thunderbird, and if the calendar is in the net and the functionality is different or if I use the web interface, althougth I change the title, no notification is sent.

I have to say I am using full day event.

Thanks

**Comment by gohrner** [comment]
I was just about to report the same bug/issue and stumbled across this earlier report.

From my point of view, updates to quite a bit of an event's metadata can be significant for attendees.

Concerning the location, it's even mentioned in the RFC section you referenced:

> In addition, changes made by the "Organizer" to other properties MAY
> also require the sequence number to be incremented.  The "Organizer"
> CUA MUST increment the sequence number whenever it makes changes to
> properties in the calendar component that the "Organizer" deems will
> jeopardize the validity of the participation status of the
> "Attendees".  For example, changing the location of a meeting from
> one location to another distant location could effectively impact the
> participation status of the "Attendees".

The same probably holds if no location was specified at all and is added later. Even though, NextCloud does not send an update even in this case.

Generally, the quoted section does not forbid to send updates for other meta data changes at all. It just requires to send them in cases which may invalidate the attendees' participation status - it does not say anything about not increasing the sequence number (which seems to be equivalent to sending out updates?) for other meta data changes.

In my experience, the description, location and also meeting title can contain information which is important for the (potential or also confirmed) attendees' to know / to be informed about.

It was a big surprise to me that NextCloud Calendar does *not* actually send updates in this case.

**Comment by gohrner** [comment]
BTW, I quote another paragraph from this section:

> Whilst a change in sequence number is indicative of a significant
> change to a previously scheduled item, "Attendee" CUAs SHOULD NOT
> rely solely on a change in sequence number as a means of detecting a
> significant change.  Instead, CUAs SHOULD compare the old and new
> versions of the calendar components, determine the exact nature of
> the changes, and make decisions -- possibly based on "Calendar User"
> preferences -- as to whether the user needs to be explicitly informed
> of the change.

So a Sequence Number change is not even required for a notification to be sent out.

**Comment by georgehrke** [comment]
> So a Sequence Number change is not even required for a notification to be sent out.

This is already the case. The server sends out notifications as soon as any of the listed properties change:
https://github.com/nextcloud/3rdparty/blob/214c4155f587f5178d792fe4a839044bdc9982f1/sabre/vobject/lib/ITip/Broker.php#L69

**Comment by georgehrke** [comment]
to summarise: 

Properties that should be considered a significant change as well:
- SUMMARY
- LOCATION
- DESCRIPTION

**Comment by gohrner** [comment]
> > So a Sequence Number change is not even required for a notification to be sent out.
> This is already the case. The server sends out notifications as soon as any of the listed properties change:

Ah, cool.



> to summarise: Properties that should be considered a significant change as well:
> * SUMMARY
> * LOCATION
> * DESCRIPTION

From my point of view: Yes.

I'd even vote for reminder changes to be significant, but here we're probably getting into the "matter of taste" twilight zone which lead the RfC's authors include the "possibly based on 'Calendar User' preferences" sub-sentence...

So it'd be cool if also reminder changes would trigger a notification, but in case of SUMMARY, LOCATION and DESCRIPTION I'd consider this to be essential.

**Comment by gohrner** [comment]
Why is the "needs info" tag still attached, what information are you currently waiting for?

**Comment by tbabej** [comment]
I think we can agree that if a location of the event changes, the attendees should be informed :) otherwise the utility of that feature decreases drastically.

At our company, this has been identified as one of the pain points of using Nextcloud's calendar internally. Adding a bounty of 50$ here.

**Comment by georgehrke** [comment]
@tbabej They are, just not for all changes. :)

Would you agree that adding the three properties mentioned above cover all use-cases?

**Comment by tbabej** [comment]
@georgehrke In general, yes, basically anything that is exposed within NextCloud Calendar UI on the "Details" tab - summary, time, location and description should inform the attendees upon change.

**Comment by yekibud** [comment]
So I guess this issue should be re-opened since I don't think it was ever fixed in #926 and since you changed the title and placed a bounty @jospoortvliet ?

Although should this go in `calendar` or `server` since the part to be changed is in `3rdparty/sabre`, IIUC https://github.com/nextcloud/3rdparty/blob/master/sabre/vobject/lib/ITip/Broker.php#L69

I'm fine with adding the suggested extra significant properties here, or having them be user configurable, if that's the general preference.

**Comment by flortsch** [comment]
I think this is still not completed, and the mentioned properties in https://github.com/nextcloud/3rdparty/blob/master/sabre/vobject/lib/ITip/Broker.php#L69 should be adopted.

**Comment by jospoortvliet** [comment]
> So I guess this issue should be re-opened since I don't think it was ever fixed in #926 and since you changed the title and placed a bounty @jospoortvliet ?
> 
> Although should this go in `calendar` or `server` since the part to be changed is in `3rdparty/sabre`, IIUC https://github.com/nextcloud/3rdparty/blob/master/sabre/vobject/lib/ITip/Broker.php#L69
> 
> I'm fine with adding the suggested extra significant properties here, or having them be user configurable, if that's the general preference.

sorry that is automatic stuff ;-)
perhaps time to turn that off...

**Comment by gohrner** [comment]
@jospoortvliet:
> sorry that is automatic stuff ;-)
> perhaps time to turn that off...

Turn what off?

Sending notifications about meeting updates altogether?
Or adding bounty markers to issues?

**Comment by jospoortvliet** [comment]
The bounty markers, yes. I am otherwise not active here, sorry...

**Comment by flortsch** [comment]
How is the 3rdparty repository handled in Nextcloud? Can the https://github.com/nextcloud/3rdparty/blob/master/sabre/vobject/lib/ITip/Broker.php file in the `sabre` library be patched within that repository (a PR that can be provided easily) or are those libraries pulled from upstream where no change is permitted?
