### ISSUE TITLE
Wrong mobile viewport height calculation leads to hidden buttons in portrait mode (if toolbar is shown)

### ISSUE THREAD

**Issue by pheraph** [nextcloud/calendar#946]
I cannot tell when this began to happen as I rarely enter the webUI for the calendar. But in the current version the buttons to save and cancel a new event aren’t shown in portrait mode. Same for editing an existing event although there the upper border of the button is shown, but it is impossible to scroll down to it. Apparently Android is also affected by this bug (https://help.nextcloud.com/t/calendar-on-phone-web-browser-no-save-button/40789). Rotating the device to landscape reveals the buttons. 

![93ca7147-eee1-4af1-aeb9-ec6aac15430e](https://user-images.githubusercontent.com/58503/48658081-10776e80-ea3c-11e8-9002-0ecccad31c07.jpeg)

![26f89954-6181-4978-bd32-3d898f739cc3](https://user-images.githubusercontent.com/58503/48658080-10776e80-ea3c-11e8-8207-c911f1560668.jpeg)

### Steps to reproduce
1. Create a new event in portrait mode
2. Enter event title

### Expected behaviour
Save button should be shown

### Actual behaviour
Save button is missing

### Server configuration

**Database:** MySQL 10.3.10

**PHP version:** 7.1.24

**Server version:** 14.0.3

**Calendar version:** 1.6.3

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - registration: 0.4.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - caniupdate
  - encryption
  - files_external
  - firstrunwizard
  - gallery
  - notes
  - user_external
  - user_ldap
```

### Client configuration

**Device:** iPhone X

**Browser:** Safari

**Operating system:** iOS 12.1

**Comment by alexanderdd** [comment]
It works fine with Android 4.4.4 and Firefox 63.0.2, Nextcloud 13.0.1 and calendar 1.6.1.
The buttons are always visible/tappable.

**Comment by pheraph** [comment]
The reason for the problem is this:

> Lengths defined in viewport units (i.e. vh) will not resize in response to the URL bar being shown or hidden. Instead, vh units will be sized to the viewport height as if the URL bar is always hidden. That is, vh units will be sized to the "largest possible viewport". This means 100vh will be larger than the visible height when the URL bar is shown. (https://developers.google.com/web/updates/2016/12/url-bar-resizing)

The current calculation of the container height is this (which translates to: take the space as if the toolbar was hidden minus the fixed height of the nextcloud header):

```css
#app-sidebar {
  height: calc(100vh - 50px);
}
```

And this leads to the buttons being under the bottom browser as seen in my screenshot. There are ways to calculate the actual viewport height in JS, but I "fixed" it for me by reducing the container height just a little more:

```css
#app-sidebar {
  height: calc(100vh - 150px);
}
```

**Comment by georgehrke** [comment]
cc @skjnldsv This is a server issue, right?

**Comment by skjnldsv** [comment]
Isn't is fixed with 14?
The structure cleanup stopped using viewport and migrated to screen percentage for this exact reason. Now if you have a toolbar or a navigation bar like iOS on the bottom, it still works fine :)

**Comment by skjnldsv** [comment]
@pheraph Well, then we can close.
This is a minor bug and fixes in stable versions :)

**Comment by pheraph** [comment]
@skjnldsv Could you please elaborate on this? The bug still appears here with Nextcloud 14. Why did you close it?

**Comment by skjnldsv** [comment]
@pheraph This is fixed on 15 and since this require really big changes, it won't be backported to 14 :)
We only backport security issues or really small fixes :/

**Comment by pheraph** [comment]
Thanks, now I understand.
